Fixed for issue#965
leo-project/leo_s3_libs pull request #13
Opened 2018-07-25 07:17 UTC by yosukehara

I've fixed both create_user's transaction and import_user's transaction.

2018-07-25 08:25 UTC, mocchira requested changes
Please check the review comments out.

2018-07-25 08:25 UTC, mocchira commented on src/leo_s3_user.erl
> +    end.
It would be good to write the erlang error handling in the `let it crash` way when writing a closure given to mnesia:activity because mensia:rollback will be called properly in case any errors (including runtime errors) happen inside the closure.

So we can rewrite like below
```erlang
ok = mnesia:write(?USERS_TABLE,
                 #?S3_USER{id = UserId,
                           password = Digest,
                           created_at = CreatedAt,
                           updated_at = CreatedAt}, write),
%% create a key
case leo_s3_auth:create_key(UserId) of
    {ok, Keys} ->
        AccessKeyId = leo_misc:get_value(access_key_id, Keys),
        ok = mnesia:write(?USER_CREDENTIAL_TABLE,
                                      #user_credential{user_id = UserId,
                                                       access_key_id = AccessKeyId,
                                                       created_at = CreatedAt}, write),
        {ok, Keys};
    Error ->
        Error
end.
```
In this way, the number of branches get smaller and make it easy to read the code.

2018-07-25 08:25 UTC, mocchira commented on src/leo_s3_user.erl
> +    end.
I think mnesia:write called inside https://github.com/leo-project/leofs/blob/v1/apps/leo_manager/src/leo_manager_console.erl#L2119-L2121 leo_s3_user:update/1 also should be included in mnesia:activity to make the whole operation atomic.

2018-07-25 08:25 UTC, mocchira commented on src/leo_s3_user.erl
> +            {error, transaction_abort}
As I said at the above comment, I'd recommend you write the code in the `let it crash` way to make the code simple and readable while the rollback is properly called in case any errors happen.

2018-07-25 08:25 UTC, mocchira commented on src/leo_s3_user.erl
> +
I think mnesia:write called inside https://github.com/leo-project/leofs/blob/v1/apps/leo_manager/src/leo_manager_console.erl#L2163-L2165 leo_s3_user:update/1 also should be included in mnesia:activity to make the whole operation atomic.

2018-07-26 05:45 UTC, mocchira requested changes
mnesia:write function calls in leo_s3_user:update invoked at leo_manager_console should be included in each transaction. Without this fix, the password field may not be updated to SecretAccessKey.

2018-07-26 05:45 UTC, mocchira commented on src/leo_s3_user.erl
> +                                       created_at = CreatedAt}, write),
As I suggested at the previous review comment, I think mnesia:write called inside https://github.com/leo-project/leofs/blob/v1/apps/leo_manager/src/leo_manager_console.erl#L2119-L2121 leo_s3_user:update/1 also should be included in this transaction to make the whole mnesia operation atomic. (The password field should be updated to SecretAccessKey)

2018-07-26 05:45 UTC, mocchira commented on src/leo_s3_user.erl
> +                                       created_at = CreatedAt}, write),
Ditto.
I think mnesia:write called inside https://github.com/leo-project/leofs/blob/v1/apps/leo_manager/src/leo_manager_console.erl#L2163-L2165 leo_s3_user:update/1 also should be included in this transaction to make the whole mnesia operation atomic. (The password field should be updated to SecretAccessKey)

2018-07-27 05:42 UTC, yosukehara commented
@mocchira PTAL

2018-07-27 22:42 UTC, mocchira approved these changes
LGTM.

2018-07-27 22:43 UTC, merged

2018-07-27 22:44 UTC, mocchira commented
Please bump the version for the upcoming leo_manager's PR.